services:
  storefromtapp:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8081"
      - "5005:5005"
    volumes:
      - .:/storefront:z
    networks:
      - ecomerce-net
networks:
  ecomerce-net:
    name: ecomerce-net
    external: true
volumes:
  db: